/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import static java.lang.Character.toUpperCase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;


/**
 *
 * @author meme
 */
public class CreatAcc extends javax.swing.JFrame {
    

    /**
     * Creates new form CreatAcc
     */
    
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Statement stmt = null;
    
    public CreatAcc() {
        initComponents();
        con=db.java_db();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fnTxt = new javax.swing.JTextField();
        lnTxt = new javax.swing.JTextField();
        pnTxt = new javax.swing.JTextField();
        emTxt = new javax.swing.JTextField();
        terms = new javax.swing.JLabel();
        agreeCB = new javax.swing.JCheckBox();
        conbtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        backbtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        mnTxt = new javax.swing.JTextField();

        jTextField5.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(208, 122, 45), 10));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FILMAX", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kohinoor Bangla", 1, 14), new java.awt.Color(208, 122, 45))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(208, 122, 45));
        jLabel1.setText("Create New Account");

        jLabel2.setText("First Name:");

        jLabel3.setText("Last Name:");

        jLabel4.setText("Phone Number:");

        jLabel5.setText("Email:");

        fnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fnTxtMouseClicked(evt);
            }
        });

        lnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lnTxtMouseClicked(evt);
            }
        });

        pnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnTxtMouseClicked(evt);
            }
        });

        emTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emTxtMouseClicked(evt);
            }
        });

        terms.setText("Agree to terms and conditions");

        conbtn.setText("Continue");
        conbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conbtnActionPerformed(evt);
            }
        });

        jLabel10.setText("Send me events and offers");

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel11.setText("Middle name:");

        mnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnTxtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(agreeCB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(terms))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(conbtn))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(18, 18, 18)
                            .addComponent(mnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(emTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(pnTxt)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(29, 29, 29)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fnTxt)
                                .addComponent(lnTxt)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jLabel1))))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(mnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(emTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(terms)
                    .addComponent(agreeCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backbtn)
                    .addComponent(conbtn))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void conbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conbtnActionPerformed
        
        if(!agreeCB.isSelected()){
            JOptionPane.showMessageDialog(null,"You have to agree to terms and conditions");
        }
        else{
        try{
            String sql ="insert into customer" 
                    +"(Fname, Mname, Lname, username, password, email, phonenum)"
                    +"values(?,?,?,?,?,?,?)";
 
            pst=con.prepareStatement(sql);
           int count=0;
            pst.setString(1, fnTxt.getText());
            pst.setString(2, mnTxt.getText());
            pst.setString(3, lnTxt.getText());
            pst.setString(6, emTxt.getText());
            pst.setString(7, pnTxt.getText());
            
            
//              LocalDate dateObj = LocalDate.now();
//              DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
//              String date = dateObj.format(formatter);
//              
//            pst.setString(9, date);
            char f=toUpperCase(fnTxt.getText().charAt(0));
            char m=toUpperCase(mnTxt.getText().charAt(0));
            char l=toUpperCase(lnTxt.getText().charAt(0));
            
            Random rand = new Random();
            
            int random=rand.nextInt((999-111)+1)+111;
            
            String l1=l+lnTxt.getText().substring(1);
            
            String pass=(f+""+m+l+random);
            String user=(f+""+m+l1);
            
            pst.setString(4, user);
            pst.setString(5, pass);

            pst.execute();
            
           
            
            JOptionPane.showMessageDialog(null,"Your username: "+user+" Your password: "+pass,"Username and Password",JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(null, fnTxt.getText()+" "+lnTxt.getText()+" added successfully!");
            
            customerLogin a = new customerLogin();
             a.setVisible(true);
             this.setVisible(false);
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "",JOptionPane.ERROR_MESSAGE);
        }
        finally{
            try{
//                rs.close();
                pst.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage(),"",JOptionPane.ERROR_MESSAGE);
            }
        }}
    }//GEN-LAST:event_conbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
       customerLogin c = new customerLogin();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backbtnActionPerformed

    private void fnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fnTxtMouseClicked
        
        checkspn=pnTxt.getText();
        checksfn=fnTxt.getText();
        checksmn=mnTxt.getText();
        checksln=lnTxt.getText();
        checksem=emTxt.getText();
        
        if(!checksem.equals("")){
            if(!checkEM(checksem)){
                JOptionPane.showMessageDialog(null, " Invalid Email!");
                emTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        
        if(!checkspn.equals("")){
            if(!checkPN(checkspn)){
                JOptionPane.showMessageDialog(null, "Invalid phone number!");
                pnTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        }
      
        if(!checksfn.equals("")){
            if(!checkName(checksfn)){
                JOptionPane.showMessageDialog(null, " Invalid first name!");
                fnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksmn.equals("")){
            if(!checkName(checksmn)){
                JOptionPane.showMessageDialog(null, " Invalid middle name!");
                mnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksln.equals("")){
            if(!checkName(checksln)){
                JOptionPane.showMessageDialog(null, " Invalid last name!");
                lnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
    }//GEN-LAST:event_fnTxtMouseClicked

    private void mnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnTxtMouseClicked
        checkspn=pnTxt.getText();
        checksfn=fnTxt.getText();
        checksmn=mnTxt.getText();
        checksln=lnTxt.getText();
        checksem=emTxt.getText();
        
        if(!checksem.equals("")){
            if(!checkEM(checksem)){
                JOptionPane.showMessageDialog(null, " Invalid Email!");
                emTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        
        if(!checkspn.equals("")){
            if(!checkPN(checkspn)){
                JOptionPane.showMessageDialog(null, "Invalid phone number!");
                pnTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        }
      
        if(!checksfn.equals("")){
            if(!checkName(checksfn)){
                JOptionPane.showMessageDialog(null, " Invalid first name!");
                fnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksmn.equals("")){
            if(!checkName(checksmn)){
                JOptionPane.showMessageDialog(null, " Invalid middle name!");
                mnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksln.equals("")){
            if(!checkName(checksln)){
                JOptionPane.showMessageDialog(null, " Invalid last name!");
                lnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
    }//GEN-LAST:event_mnTxtMouseClicked

    private void lnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lnTxtMouseClicked
        checkspn=pnTxt.getText();
        checksfn=fnTxt.getText();
        checksmn=mnTxt.getText();
        checksln=lnTxt.getText();
        checksem=emTxt.getText();
        
        if(!checksem.equals("")){
            if(!checkEM(checksem)){
                JOptionPane.showMessageDialog(null, " Invalid Email!");
                emTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        
        if(!checkspn.equals("")){
            if(!checkPN(checkspn)){
                JOptionPane.showMessageDialog(null, "Invalid phone number!");
                pnTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        }
      
        if(!checksfn.equals("")){
            if(!checkName(checksfn)){
                JOptionPane.showMessageDialog(null, " Invalid first name!");
                fnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksmn.equals("")){
            if(!checkName(checksmn)){
                JOptionPane.showMessageDialog(null, " Invalid middle name!");
                mnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksln.equals("")){
            if(!checkName(checksln)){
                JOptionPane.showMessageDialog(null, " Invalid last name!");
                lnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
    }//GEN-LAST:event_lnTxtMouseClicked

    private void pnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTxtMouseClicked
        checkspn=pnTxt.getText();
        checksfn=fnTxt.getText();
        checksmn=mnTxt.getText();
        checksln=lnTxt.getText();
        checksem=emTxt.getText();
        
        if(!checksem.equals("")){
            if(!checkEM(checksem)){
                JOptionPane.showMessageDialog(null, " Invalid Email!");
                emTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        
        if(!checkspn.equals("")){
            if(!checkPN(checkspn)){
                JOptionPane.showMessageDialog(null, "Invalid phone number!");
                pnTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        }
      
        if(!checksfn.equals("")){
            if(!checkName(checksfn)){
                JOptionPane.showMessageDialog(null, " Invalid first name!");
                fnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksmn.equals("")){
            if(!checkName(checksmn)){
                JOptionPane.showMessageDialog(null, " Invalid middle name!");
                mnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksln.equals("")){
            if(!checkName(checksln)){
                JOptionPane.showMessageDialog(null, " Invalid last name!");
                lnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
    }//GEN-LAST:event_pnTxtMouseClicked

    private void emTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emTxtMouseClicked
        checkspn=pnTxt.getText();
        checksfn=fnTxt.getText();
        checksmn=mnTxt.getText();
        checksln=lnTxt.getText();
        checksem=emTxt.getText();
        
        if(!checksem.equals("")){
            if(!checkEM(checksem)){
                JOptionPane.showMessageDialog(null, " Invalid Email!");
                emTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        
        if(!checkspn.equals("")){
            if(!checkPN(checkspn)){
                JOptionPane.showMessageDialog(null, "Invalid phone number!");
                pnTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        }
      
        if(!checksfn.equals("")){
            if(!checkName(checksfn)){
                JOptionPane.showMessageDialog(null, " Invalid first name!");
                fnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksmn.equals("")){
            if(!checkName(checksmn)){
                JOptionPane.showMessageDialog(null, " Invalid middle name!");
                mnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksln.equals("")){
            if(!checkName(checksln)){
                JOptionPane.showMessageDialog(null, " Invalid last name!");
                lnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
    }//GEN-LAST:event_emTxtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreatAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreatAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreatAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreatAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreatAcc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox agreeCB;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton conbtn;
    private javax.swing.JTextField emTxt;
    private javax.swing.JTextField fnTxt;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField lnTxt;
    private javax.swing.JTextField mnTxt;
    private javax.swing.JTextField pnTxt;
    private javax.swing.JLabel terms;
    // End of variables declaration//GEN-END:variables

private String checkspn="";
private String checksfn="";
private String checksmn="";
private String checksln="";
private String checksem="";
private static boolean add;

public static boolean checkName(String checksname){
    boolean valid=true;
    for (char c : checksname.toCharArray()){
        if(Character.isDigit(c))
            valid =false;
    }
    return valid;    
}

public static boolean checkEM(String checksem){
    boolean valid=false; 
    if(checksem.contains(".com") && checksem.contains("@"))
        valid=true;
        
    return valid;
}

public static boolean checkPN(String checkspn){
     boolean valid=false; 
     if(checkspn.length()==10&&checkspn.startsWith("05")){
        for (char c : checkspn.toCharArray()){
            if(!Character.isDigit(c)){
                valid = false;
                break;
            }
            else{
                valid=true;
            }
        }
     }
        return valid;   
}

}
