/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.sql.*;
import java.awt.*;
import static java.lang.Character.toUpperCase;
import javax.swing.*;
import java.util.*;

/**
 *
 * @author meme
 */
public class CreateAdd extends javax.swing.JFrame {

    /**
     * Creates new form CreateAdd
     */
    
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Statement stmt = null;
    
    public CreateAdd() {
        
        initComponents();
        con=db.java_db();
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        fnTxt = new javax.swing.JTextField();
        mnTxt = new javax.swing.JTextField();
        lnTxt = new javax.swing.JTextField();
        clrBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        sIdTxt = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        addTxt = new javax.swing.JTextField();
        pnTxt = new javax.swing.JTextField();
        emTxt = new javax.swing.JTextField();
        khBtn = new javax.swing.JRadioButton();
        dmmBtn = new javax.swing.JRadioButton();
        addBtn = new javax.swing.JButton();
        updBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        searchBar = new javax.swing.JTextField();
        srchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(208, 122, 45), 10));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(208, 122, 45));
        jLabel1.setText("Admin Management");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FILMAX", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kohinoor Bangla", 1, 13), new java.awt.Color(208, 122, 45))); // NOI18N

        jLabel31.setFont(new java.awt.Font("Hei", 0, 13)); // NOI18N
        jLabel31.setText("First Name:");

        jLabel32.setFont(new java.awt.Font("Hei", 0, 13)); // NOI18N
        jLabel32.setText("Middle Name:");

        jLabel33.setFont(new java.awt.Font("Hei", 0, 13)); // NOI18N
        jLabel33.setText("Last Name:");

        fnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fnTxtMouseClicked(evt);
            }
        });
        fnTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnTxtActionPerformed(evt);
            }
        });
        fnTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnTxtKeyTyped(evt);
            }
        });

        mnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnTxtMouseClicked(evt);
            }
        });
        mnTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTxtActionPerformed(evt);
            }
        });
        mnTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mnTxtKeyTyped(evt);
            }
        });

        lnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lnTxtMouseClicked(evt);
            }
        });
        lnTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnTxtActionPerformed(evt);
            }
        });
        lnTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lnTxtKeyTyped(evt);
            }
        });

        clrBtn.setText("Clear");
        clrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Hei", 0, 13)); // NOI18N
        jLabel42.setText("Supervisor ID:");

        sIdTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sIdTxtMouseClicked(evt);
            }
        });
        sIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sIdTxtActionPerformed(evt);
            }
        });
        sIdTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sIdTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sIdTxtKeyTyped(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Hei", 0, 13)); // NOI18N
        jLabel43.setText("Phone Number:");

        jLabel44.setFont(new java.awt.Font("Hei", 0, 13)); // NOI18N
        jLabel44.setText("E-mail:");

        jLabel45.setFont(new java.awt.Font("Hei", 0, 13)); // NOI18N
        jLabel45.setText("Branch:");

        jLabel46.setFont(new java.awt.Font("Hei", 0, 13)); // NOI18N
        jLabel46.setText("Address:");

        addTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addTxtMouseClicked(evt);
            }
        });
        addTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTxtActionPerformed(evt);
            }
        });

        pnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnTxtMouseClicked(evt);
            }
        });
        pnTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnTxtActionPerformed(evt);
            }
        });
        pnTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pnTxtKeyTyped(evt);
            }
        });

        emTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emTxtMouseClicked(evt);
            }
        });
        emTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emTxtActionPerformed(evt);
            }
        });
        emTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emTxtKeyTyped(evt);
            }
        });

        buttonGroup1.add(khBtn);
        khBtn.setFont(new java.awt.Font("Hei", 0, 13)); // NOI18N
        khBtn.setText("Khobar");
        khBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(dmmBtn);
        dmmBtn.setFont(new java.awt.Font("Hei", 0, 13)); // NOI18N
        dmmBtn.setText("Dammam");
        dmmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dmmBtnActionPerformed(evt);
            }
        });

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updBtn.setText("Update");
        updBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updBtnActionPerformed(evt);
            }
        });

        delBtn.setText("Delete");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        viewBtn.setText("View All");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45)
                            .addComponent(jLabel43)
                            .addComponent(jLabel44)
                            .addComponent(jLabel42)
                            .addComponent(jLabel33))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(pnTxt)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(khBtn)
                                .addGap(18, 18, 18)
                                .addComponent(dmmBtn))
                            .addComponent(lnTxt)
                            .addComponent(addTxt)
                            .addComponent(sIdTxt)))
                    .addComponent(jLabel46)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(clrBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(fnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(mnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updBtn))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(delBtn))
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42)
                    .addComponent(viewBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(addTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(khBtn)
                    .addComponent(dmmBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43)
                    .addComponent(clrBtn))
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44)
                    .addComponent(backBtn))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        closeBtn.setForeground(new java.awt.Color(208, 122, 45));
        closeBtn.setText("X");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Hei", 1, 13)); // NOI18N
        jLabel34.setText("Search Employee:");

        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });
        searchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchBarKeyReleased(evt);
            }
        });

        srchBtn.setText("Search");
        srchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(srchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeBtn)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        adminMenu c = new adminMenu();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void clrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrBtnActionPerformed
        searchBar.setText("");
        fnTxt.setText("");
        mnTxt.setText("");
        lnTxt.setText("");
        addTxt.setText("");
        emTxt.setText("");
        pnTxt.setText("");
        sIdTxt.setText("");
        buttonGroup1.clearSelection();      
    }//GEN-LAST:event_clrBtnActionPerformed

    private void lnTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnTxtActionPerformed
      
{
        }    }//GEN-LAST:event_lnTxtActionPerformed

    private void mnTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTxtActionPerformed
   
    }//GEN-LAST:event_mnTxtActionPerformed

    private void fnTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnTxtActionPerformed
 
    }//GEN-LAST:event_fnTxtActionPerformed

    private void sIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sIdTxtActionPerformed
   
    }//GEN-LAST:event_sIdTxtActionPerformed

    private void addTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTxtActionPerformed

    private void pnTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnTxtActionPerformed
        {
        }    }//GEN-LAST:event_pnTxtActionPerformed

    private void emTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emTxtActionPerformed
     
    }//GEN-LAST:event_emTxtActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
    
        if(add){
            try{
                String sql = "insert into employee"
                        +"(superviserID, first_name, middle_name, last_name, address,"
                        +"id_branch, phoneNo, email, username, password)"
                        +"values(?,?,?,?,?,?,?,?,?,?)";
                pst=con.prepareStatement(sql);
                
                pst.setInt(1, Integer.parseInt(sIdTxt.getText()));
                pst.setString(2, fnTxt.getText());
                pst.setString(3, mnTxt.getText());
                pst.setString(4, lnTxt.getText());
                pst.setString(5, addTxt.getText());
                pst.setInt(6, branchID);
                pst.setString(7, pnTxt.getText());
                pst.setString(8, emTxt.getText());

                char f=toUpperCase(fnTxt.getText().charAt(0));
                char m=toUpperCase(mnTxt.getText().charAt(0));
                char l=toUpperCase(lnTxt.getText().charAt(0));

                Random rand = new Random();

                int random=rand.nextInt((999-111)+1)+111;

                String l1=l+lnTxt.getText().substring(1);

                String pass=(f+""+m+l+random);
                String user=(f+""+m+l1);

                pst.setString(9, user);
                pst.setString(10, pass);

                pst.execute();
                JOptionPane.showMessageDialog(null,"Your username: "+user+" Your password: "+pass,"Username and Password",JOptionPane.INFORMATION_MESSAGE);
                JOptionPane.showMessageDialog(null, fnTxt.getText()+" "+lnTxt.getText()+" added successfully!");
                

//                }
            }

            catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage(), "",JOptionPane.ERROR_MESSAGE);
            }
            finally{
                try{

                    pst.close();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e.getMessage(),"",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        else
            JOptionPane.showMessageDialog(null,"An error occurred, make sure all fields are filled with valid information");

            
    }//GEN-LAST:event_addBtnActionPerformed

    private void khBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khBtnActionPerformed
        branchID = 1;
        khBtn.setSelected(true);
        dmmBtn.setSelected(false);
    }//GEN-LAST:event_khBtnActionPerformed

    private void dmmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dmmBtnActionPerformed
        branchID = 2;
        khBtn.setSelected(false);
        dmmBtn.setSelected(true);
    }//GEN-LAST:event_dmmBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirm exit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(response == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_closeBtnActionPerformed

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarActionPerformed

    private void updBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updBtnActionPerformed

        if(fnTxt.getText().equals("")||mnTxt.getText().equals("")||lnTxt.getText().equals("")
            ||pnTxt.getText().equals("")||emTxt.getText().equals("")
        ){
        JOptionPane.showMessageDialog(null, "Some required fileds are empty!","Fill All Fields",JOptionPane.ERROR_MESSAGE);
        }
        else{
        int updateR = JOptionPane.showConfirmDialog(this, "Are you sure you want to update "+fnTxt.getText()+" "+lnTxt.getText()+"'s information?", "Confirm update", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(updateR == JOptionPane.YES_OPTION){
            try{
                String fn = fnTxt.getText();
                String mn = mnTxt.getText();
                String ln = lnTxt.getText();
               String sid = sIdTxt.getText();
                String add = addTxt.getText();
                String pn = pnTxt.getText();
                String em = emTxt.getText();
                String branch;

                if(khBtn.isSelected())
                    branch="Khobar";

                else if(dmmBtn.isSelected())
                    branch="Dammam";

                else
                    branch=null;
                

                    try{

                    int branchID=0;

                    if(khBtn.isSelected())
                        branchID=1;

                    else if(dmmBtn.isSelected())
                        branchID=2;

                    else
                        branchID=0;
                    
                    
            for (char c : fn.toCharArray()){
            if(Character.isAlphabetic(c))
            checksfnb1 =true;
            else
             checksfnb1 =false;   
             }
            
            String s="";
            boolean checkall = true;
            
                    if (!checksfnb1){
                      s+= "\nInvalid First Name";  
                        checkall = false;
                        fnTxt.setText("");
                    }
                    else{
                       checkall = true; 
                    }
                for (char c : mn.toCharArray()){
            if(Character.isAlphabetic(c))
            checksmnb1 =true;
            else
             checksmnb1 =false;   
             }       
                    
                     if (!checksmnb1){
                      s+= "\nInvalid Middle Name";  
                        checkall = false;
                        mnTxt.setText("");
                    }
                    else{
                       checkall = true; 
                    }
                    
                     for (char c : ln.toCharArray()){
            if(Character.isAlphabetic(c))
            checkslnb1 =true;
            else
             checkslnb1 =false;   
             }       
                    
                     if (!checkslnb1){
                      s+= "\nInvalid Last Name";  
                        checkall = false;
                        lnTxt.setText("");
                    }
                    else{
                       checkall = true; 
                    }   
                     
                for (char c : sid.toCharArray()){
            if(Character.isDigit(c))
            checksIDb1 =true;
            else
             checksIDb1 =false;   
        }     
                     
                         if (!checksIDb1){
                      s+= "\nInvalid Supervisor ID";  
                        checkall = false;
                        sIdTxt.setText("");
                    }
                    else{
                       checkall = true; 
                    } 
                         
                         
        if(pnTxt.getText().length()==10 && pnTxt.getText().startsWith("05")){
            for (char c : pnTxt.getText().toCharArray()){
                if(Character.isDigit(c))
                    checkspnb1 =true;
                    else
                     checkspnb1 =false;   
                     }
                 }
              if (!checkspnb1){
                      s+= "\nInvalid Phone Number";  
                        checkall = false;
                        pnTxt.setText("");
                    }
                    else{
                       checkall = true; 
                    } 
                if(emTxt.getText().contains(".com") && emTxt.getText().contains("@"))
            checksemb1 =true;
            else
             checksemb1 =false;   
              
               if (!checksemb1){
                      s+= "\nInvalid email";  
                        checkall = false;
                         emTxt.setText("");
                    }
                    else{
                       checkall = true; 
                    } 
                      
                  if(!checkall)   {
                JOptionPane.showMessageDialog(null, s, "",JOptionPane.ERROR_MESSAGE);
 
                      
                  }
                  
                  else{
                       String info="Is the following information correct?\nFirst name: "+fn
                        +"\nMiddle name: "+mn+"\nLast name: "+ln+"\nSupervisor ID: "
                        +sid+"\nAddress: "+add+"\nBranch: "+branch+"\nPhone number: "
                        +pn+"\nEmail: "+em;
                
                int infoR = JOptionPane.showConfirmDialog(this, info , "Confirm information", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                            if(infoR == JOptionPane.YES_OPTION){ 
                
                String sql= "update employee set first_name='"+fn+"', middle_name='"+mn+"', last_name='"+ln
                            +"', address='"+add+"', superviserID= "+sid+", id_branch="+branchID+",phoneNo='"+pn+"', email='"+em+"' where id="
                            +searchBar.getText();

                        pst=con.prepareStatement(sql);
                        pst.execute();
                        JOptionPane.showMessageDialog(null, "Record updated sucessfully!", "",JOptionPane.INFORMATION_MESSAGE);
                            }    }


                    searchBar.setText("");
                    fnTxt.setText("");
                    mnTxt.setText("");
                    lnTxt.setText("");
                    addTxt.setText("");
                    emTxt.setText("");
                    pnTxt.setText("");
                    sIdTxt.setText("");
                    buttonGroup1.clearSelection();
                    
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e.getMessage(), "",JOptionPane.ERROR_MESSAGE);
                }
                finally{
                    try{
                        pst.close();
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, e.getMessage(),"",JOptionPane.ERROR_MESSAGE);
                    }
                }
                
                
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage(), "",JOptionPane.ERROR_MESSAGE);
            }
            finally{
                try{

                    pst.close();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e.getMessage(),"",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        else {
            int response3 = JOptionPane.showConfirmDialog(this, "Clear all information?", "Confirm clear", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(response3 == JOptionPane.YES_OPTION){
                searchBar.setText("");
                fnTxt.setText("");
                mnTxt.setText("");
                lnTxt.setText("");
                addTxt.setText("");
                emTxt.setText("");
                pnTxt.setText("");
                sIdTxt.setText("");
                buttonGroup1.clearSelection();
            }
        }
   
            
        }   
    }//GEN-LAST:event_updBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete "+fnTxt.getText()+" "+lnTxt.getText()+"?", "Confirm delete", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(response == JOptionPane.YES_OPTION){
            try{
                String sql="delete from employee where id=?";
                pst=con.prepareStatement(sql);
                pst.setString(1,searchBar.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null, fnTxt.getText()+" "+lnTxt.getText()+" deleted successfully");
                searchBar.setText("");
                fnTxt.setText("");
                mnTxt.setText("");
                lnTxt.setText("");
                addTxt.setText("");
                emTxt.setText("");
                pnTxt.setText("");
                sIdTxt.setText("");
                buttonGroup1.clearSelection();

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage(), "",JOptionPane.ERROR_MESSAGE);
            }
            finally{
                try{
    //                rs.close();
                    pst.close();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e.getMessage(),"",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        else {
            int response2 = JOptionPane.showConfirmDialog(this, "Clear all information?", "Confirm clear", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(response2 == JOptionPane.YES_OPTION){
                searchBar.setText("");
                fnTxt.setText("");
                mnTxt.setText("");
                lnTxt.setText("");
                addTxt.setText("");
                emTxt.setText("");
                pnTxt.setText("");
                sIdTxt.setText("");
                buttonGroup1.clearSelection();
            }

        }
        
        
        
    }//GEN-LAST:event_delBtnActionPerformed

    private void searchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBarKeyReleased

    }//GEN-LAST:event_searchBarKeyReleased

    private void srchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchBtnActionPerformed
        try{
            String sql="select * from employee where id=?";
            pst=con.prepareStatement(sql);
            pst.setInt(1,Integer.parseInt(searchBar.getText()));
            rs=pst.executeQuery();
            
            if(rs.next()==false){
                JOptionPane.showMessageDialog(null, "Employee does not exist, try another ID.","",JOptionPane.INFORMATION_MESSAGE);
                searchBar.setText("");
                fnTxt.setText("");
                mnTxt.setText("");
                lnTxt.setText("");
                addTxt.setText("");
                emTxt.setText("");
                pnTxt.setText("");
                sIdTxt.setText("");
                buttonGroup1.clearSelection();
            }
            else{
                String fn=rs.getString("first_name");
                fnTxt.setText(fn);
                String mn=rs.getString("middle_name");
                mnTxt.setText(mn);
                String ln=rs.getString("last_name");
                lnTxt.setText(ln);
                String add=rs.getString("address");
                addTxt.setText(add);
                String pn=rs.getString("phoneNo");
                pnTxt.setText(pn);
                String em=rs.getString("email");
                emTxt.setText(em);
                int sId=rs.getInt("superviserID");
                sIdTxt.setText(Integer.toString(sId));
                int branchId=rs.getInt("id_branch");
                switch (branchId) {
                    case 1:
                        khBtn.setSelected(true);
                        dmmBtn.setSelected(false);
                        break;
                    case 2:
                        khBtn.setSelected(false);
                        dmmBtn.setSelected(true);
                        break;
                    default:
                        buttonGroup1.clearSelection();
                        break;
                }
            }
            
                
            
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "",JOptionPane.ERROR_MESSAGE);
        }
        finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage(),"",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_srchBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        tableView t = new tableView();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_viewBtnActionPerformed

    private void sIdTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sIdTxtKeyTyped
//       checksID = evt.getKeyChar();
//       checksIDb= Character.isDigit(checksID);
//       if(!checksIDb)
//       JOptionPane.showMessageDialog(null, " Invalid Supervisor ID!");
     
    }//GEN-LAST:event_sIdTxtKeyTyped

    private void fnTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnTxtKeyTyped
//        checksfn = evt.getKeyChar();
    }//GEN-LAST:event_fnTxtKeyTyped

    private void pnTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnTxtKeyTyped
//       checkspn = evt.getKeyChar();
    }//GEN-LAST:event_pnTxtKeyTyped

    private void mnTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnTxtKeyTyped
//      checksmn =evt.getKeyChar();
    }//GEN-LAST:event_mnTxtKeyTyped

    private void lnTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnTxtKeyTyped
//      checksln =evt.getKeyChar();
      
    }//GEN-LAST:event_lnTxtKeyTyped

    private void emTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emTxtKeyTyped
//      checksem =evt.getKeyChar();
      
    }//GEN-LAST:event_emTxtKeyTyped

    private void fnTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnTxtKeyReleased

    }//GEN-LAST:event_fnTxtKeyReleased

    private void sIdTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sIdTxtKeyReleased

    }//GEN-LAST:event_sIdTxtKeyReleased

    private void fnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fnTxtMouseClicked
        checksID=sIdTxt.getText();
        checkspn=pnTxt.getText();
        checksfn=fnTxt.getText();
        checksmn=mnTxt.getText();
        checksln=lnTxt.getText();
        checksem=emTxt.getText();
        checksadd=addTxt.getText();
        checksbr=branchID; 
        
        if(!checksID.equals("")){
            if(!checkID(checksID)){
                JOptionPane.showMessageDialog(null, "Invalid supervisor ID!");
                sIdTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        } 
        
        if(!checkspn.equals("")){
            if(!checkPN(checkspn)){
                JOptionPane.showMessageDialog(null, "Invalid phone number!");
                pnTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksem.equals("")){
            if(!checkEM(checksem)){
                JOptionPane.showMessageDialog(null, " Invalid Email!");
                emTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksfn.equals("")){
            if(!checkFN(checksfn)){
                JOptionPane.showMessageDialog(null, " Invalid first name!");
                fnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksmn.equals("")){
            if(!checkMN(checksmn)){
                JOptionPane.showMessageDialog(null, " Invalid middle name!");
                mnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksln.equals("")){
            if(!checkLN(checksln)){
                JOptionPane.showMessageDialog(null, " Invalid last name!");
                lnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
    }//GEN-LAST:event_fnTxtMouseClicked

    private void mnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnTxtMouseClicked
       checksID=sIdTxt.getText();
        checkspn=pnTxt.getText();
        checksfn=fnTxt.getText();
        checksmn=mnTxt.getText();
        checksln=lnTxt.getText();
        checksem=emTxt.getText();
        checksadd=addTxt.getText();
        checksbr=branchID; 
        
        if(!checksID.equals("")){
            if(!checkID(checksID)){
                JOptionPane.showMessageDialog(null, "Invalid supervisor ID!");
                sIdTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        } 
        
        if(!checkspn.equals("")){
            if(!checkPN(checkspn)){
                JOptionPane.showMessageDialog(null, "Invalid phone number!");
                pnTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksem.equals("")){
            if(!checkEM(checksem)){
                JOptionPane.showMessageDialog(null, " Invalid Email!");
                emTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksfn.equals("")){
            if(!checkFN(checksfn)){
                JOptionPane.showMessageDialog(null, " Invalid first name!");
                fnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksmn.equals("")){
            if(!checkMN(checksmn)){
                JOptionPane.showMessageDialog(null, " Invalid middle name!");
                mnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksln.equals("")){
            if(!checkLN(checksln)){
                JOptionPane.showMessageDialog(null, " Invalid last name!");
                lnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
    }//GEN-LAST:event_mnTxtMouseClicked

    private void lnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lnTxtMouseClicked
      checksID=sIdTxt.getText();
        checkspn=pnTxt.getText();
        checksfn=fnTxt.getText();
        checksmn=mnTxt.getText();
        checksln=lnTxt.getText();
        checksem=emTxt.getText();
        checksadd=addTxt.getText();
        checksbr=branchID; 
        
        if(!checksID.equals("")){
            if(!checkID(checksID)){
                JOptionPane.showMessageDialog(null, "Invalid supervisor ID!");
                sIdTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        } 
        
        if(!checkspn.equals("")){
            if(!checkPN(checkspn)){
                JOptionPane.showMessageDialog(null, "Invalid phone number!");
                pnTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksem.equals("")){
            if(!checkEM(checksem)){
                JOptionPane.showMessageDialog(null, " Invalid Email!");
                emTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksfn.equals("")){
            if(!checkFN(checksfn)){
                JOptionPane.showMessageDialog(null, " Invalid first name!");
                fnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksmn.equals("")){
            if(!checkMN(checksmn)){
                JOptionPane.showMessageDialog(null, " Invalid middle name!");
                mnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksln.equals("")){
            if(!checkLN(checksln)){
                JOptionPane.showMessageDialog(null, " Invalid last name!");
                lnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
    }//GEN-LAST:event_lnTxtMouseClicked

    private void sIdTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sIdTxtMouseClicked
      checksID=sIdTxt.getText();
        checkspn=pnTxt.getText();
        checksfn=fnTxt.getText();
        checksmn=mnTxt.getText();
        checksln=lnTxt.getText();
        checksem=emTxt.getText();
        checksadd=addTxt.getText();
        checksbr=branchID; 
        
        if(!checksID.equals("")){
            if(!checkID(checksID)){
                JOptionPane.showMessageDialog(null, "Invalid supervisor ID!");
                sIdTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        } 
        
        if(!checkspn.equals("")){
            if(!checkPN(checkspn)){
                JOptionPane.showMessageDialog(null, "Invalid phone number!");
                pnTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksem.equals("")){
            if(!checkEM(checksem)){
                JOptionPane.showMessageDialog(null, " Invalid Email!");
                emTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksfn.equals("")){
            if(!checkFN(checksfn)){
                JOptionPane.showMessageDialog(null, " Invalid first name!");
                fnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksmn.equals("")){
            if(!checkMN(checksmn)){
                JOptionPane.showMessageDialog(null, " Invalid middle name!");
                mnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksln.equals("")){
            if(!checkLN(checksln)){
                JOptionPane.showMessageDialog(null, " Invalid last name!");
                lnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
    }//GEN-LAST:event_sIdTxtMouseClicked

    private void addTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTxtMouseClicked
  checksID=sIdTxt.getText();
        checkspn=pnTxt.getText();
        checksfn=fnTxt.getText();
        checksmn=mnTxt.getText();
        checksln=lnTxt.getText();
        checksem=emTxt.getText();
        checksadd=addTxt.getText();
        checksbr=branchID; 
        
        if(!checksID.equals("")){
            if(!checkID(checksID)){
                JOptionPane.showMessageDialog(null, "Invalid supervisor ID!");
                sIdTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        } 
        
        if(!checkspn.equals("")){
            if(!checkPN(checkspn)){
                JOptionPane.showMessageDialog(null, "Invalid phone number!");
                pnTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksem.equals("")){
            if(!checkEM(checksem)){
                JOptionPane.showMessageDialog(null, " Invalid Email!");
                emTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksfn.equals("")){
            if(!checkFN(checksfn)){
                JOptionPane.showMessageDialog(null, " Invalid first name!");
                fnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksmn.equals("")){
            if(!checkMN(checksmn)){
                JOptionPane.showMessageDialog(null, " Invalid middle name!");
                mnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksln.equals("")){
            if(!checkLN(checksln)){
                JOptionPane.showMessageDialog(null, " Invalid last name!");
                lnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
    }//GEN-LAST:event_addTxtMouseClicked

    private void pnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTxtMouseClicked
        checksID=sIdTxt.getText();
        checkspn=pnTxt.getText();
        checksfn=fnTxt.getText();
        checksmn=mnTxt.getText();
        checksln=lnTxt.getText();
        checksem=emTxt.getText();
        checksadd=addTxt.getText();
        checksbr=branchID; 
        
        if(!checksID.equals("")){
            if(!checkID(checksID)){
                JOptionPane.showMessageDialog(null, "Invalid supervisor ID!");
                sIdTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        } 
        
        if(!checkspn.equals("")){
            if(!checkPN(checkspn)){
                JOptionPane.showMessageDialog(null, "Invalid phone number!");
                pnTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksem.equals("")){
            if(!checkEM(checksem)){
                JOptionPane.showMessageDialog(null, " Invalid Email!");
                emTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksfn.equals("")){
            if(!checkFN(checksfn)){
                JOptionPane.showMessageDialog(null, " Invalid first name!");
                fnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksmn.equals("")){
            if(!checkMN(checksmn)){
                JOptionPane.showMessageDialog(null, " Invalid middle name!");
                mnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksln.equals("")){
            if(!checkLN(checksln)){
                JOptionPane.showMessageDialog(null, " Invalid last name!");
                lnTxt.setText("");  
                add=false;
            }
            else{
                add=true;
            }
        }
    }//GEN-LAST:event_pnTxtMouseClicked

    private void emTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emTxtMouseClicked
   checksID=sIdTxt.getText();
        checkspn=pnTxt.getText();
        checksfn=fnTxt.getText();
        checksmn=mnTxt.getText();
        checksln=lnTxt.getText();
        checksem=emTxt.getText();
        checksadd=addTxt.getText();
        checksbr=branchID; 
        
        if(!checksID.equals("")){
            if(!checkID(checksID)){
                JOptionPane.showMessageDialog(null, "Invalid supervisor ID!");
                sIdTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        } 
        
          
    }//GEN-LAST:event_emTxtMouseClicked

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAdd().setVisible(true);
            }
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField addTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton clrBtn;
    private javax.swing.JButton delBtn;
    private javax.swing.JRadioButton dmmBtn;
    private javax.swing.JTextField emTxt;
    private javax.swing.JTextField fnTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton khBtn;
    private javax.swing.JTextField lnTxt;
    private javax.swing.JTextField mnTxt;
    private javax.swing.JTextField pnTxt;
    private javax.swing.JTextField sIdTxt;
    private javax.swing.JTextField searchBar;
    private javax.swing.JButton srchBtn;
    private javax.swing.JButton updBtn;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables

private int branchID;
private String checksID="";
private String checkspn="";
private String checksfn="";
private String checksmn="";
private String checksln="";
private String checksem="";
private String checksadd="";
private int checksbr;
private static boolean add;

public static boolean checkID(String checksID){
    boolean valid=true; 
        for (char c : checksID.toCharArray()){
            if(!Character.isDigit(c)){
                valid = false;
                break;
            }
        }
        return valid;
}

public static boolean checkFN(String checksfn){
    boolean valid=true;
    for (char c : checksfn.toCharArray()){
        if(Character.isDigit(c))
            valid =false;
    }
    return valid;
}
public static boolean checkMN(String checksmn){
     boolean valid=true;
    for (char c : checksmn.toCharArray()){
        if(Character.isDigit(c))
            valid =false;
    }
    return valid;   
}
public static boolean checkLN(String checksln){
    boolean valid=true;
    for (char c : checksln.toCharArray()){
        if(Character.isDigit(c))
            valid =false;
    }
    return valid;    
}
public static boolean checkEM(String checksem){
    boolean valid=false; 
    if(checksem.contains(".com") && checksem.contains("@"))
        valid=true;
        
    return valid;
}

public static boolean checkPN(String checkspn){
     boolean valid=false; 
     if(checkspn.length()==10&&checkspn.startsWith("05")){
        for (char c : checkspn.toCharArray()){
            if(!Character.isDigit(c)){
                valid = false;
                break;
            }
            else{
                valid=true;
            }
        }
     }
        return valid;   
}


private boolean checksfnb1;
private boolean  checksmnb1;
private boolean  checkslnb1;
private boolean  checksemb1;
private boolean checksIDb1 = false;
private boolean checkspnb1;



}
