/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author meme
 */
public class hallselection extends javax.swing.JFrame {

   Connection con =null;
   ResultSet rs = null;
   PreparedStatement pst = null;
   Statement st =null;
          
    public hallselection() {
        initComponents();
        con = db.java_db();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        hallt = new javax.swing.JTable();
        displaybtn = new javax.swing.JButton();
        bookbtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(208, 122, 45), 10));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FILMAX", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kohinoor Bangla", 0, 13), new java.awt.Color(208, 122, 45))); // NOI18N

        hallt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Hall Number", "Dates", "Timings", "Availability"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        hallt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                halltMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(hallt);

        displaybtn.setText("Display");
        displaybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaybtnActionPerformed(evt);
            }
        });

        bookbtn.setText("Assign");
        bookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bookbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displaybtn)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displaybtn)
                    .addComponent(bookbtn))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );

        exitBtn.setForeground(new java.awt.Color(208, 122, 45));
        exitBtn.setText("X");
        exitBtn.setBorder(null);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Hoefler Text", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(208, 122, 45));
        jLabel1.setText("Hall Selection");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirm exit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(response == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    private void displaybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaybtnActionPerformed
            
        String sql="select numhall, date, time , movieid  from Screenings ";
        try{
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel)hallt.getModel();
            model.setRowCount(0);
            
            
            
            while(rs.next()){
                
                String a=rs.getString(4);
//                String avail;
                if(a==null){
                    model.addRow(new Object[]{rs.getString(1),rs.getString(2),
                    rs.getString(3) , "Available"});
                }
                else{
                    model.addRow(new Object[]{rs.getString(1),rs.getString(2),
                    rs.getString(3) , "Booked"});
                }
                            
                
                
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(),"",JOptionPane.ERROR_MESSAGE);
        }
        finally{
        
        }
    }//GEN-LAST:event_displaybtnActionPerformed

    private void halltMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_halltMouseClicked
     
    }//GEN-LAST:event_halltMouseClicked

    private void bookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookbtnActionPerformed
        // TODO add your handling code here:
//        String sql="select hallnum, time, branch, availbility from showingtimes ";
        DefaultTableModel model = (DefaultTableModel)hallt.getModel();
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to assign the movie to this hall?", "Confirm assign", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(response == JOptionPane.YES_OPTION){
        
        
        try{
            st = con.createStatement();
            String chosenMovie=addMovie.movienameh;
//            JOptionPane.showMessageDialog(this,chosenMovie);
            String sql="select movieid from movie where movietitle = '"+chosenMovie+"' ";
//            pst.executeQuery(sql);
            rs = pst.executeQuery(sql);
            while(rs.next()){
                movieId = rs.getInt("movieid");
            }
//            JOptionPane.showMessageDialog(this,movieId);
            
//            for(int i =0 ; i < model.getRowCount();i++){   
                
                String hallnum=model.getValueAt(hallt.getSelectedRow(), 0).toString();
                String date =model.getValueAt(hallt.getSelectedRow(), 1).toString();
                String time=model.getValueAt(hallt.getSelectedRow(), 2).toString();
                movie_id=model.getValueAt(hallt.getSelectedRow(), 3).toString();
//            
//                JOptionPane.showMessageDialog(this,hallnum);
//                JOptionPane.showMessageDialog(this,date);
//                JOptionPane.showMessageDialog(this,time);
//                JOptionPane.showMessageDialog(this,movie_id);
                
//                String chosenMovie=addMovie.movienameh;
                int check=0 ;
                if(movie_id.equals("Available"))
                    check=0;
                
                else if (movie_id.equals("Booked"))
                     check=1;
            
                if (check==0){
                String update="UPDATE screenings SET movieid = '"+movieId+"' WHERE (numhall = '"+ hallnum+ "') and (time = '"+time+"') and (date = '"+date+"')";
//                pst.executeQuery(update);
                String UpdateM = "update Movie SET Hallnum ='"+hallnum+"' WHERE ( MovieTitle ='"+addMovie.movienameh+"')";
//                String update="update showingtimes set Availbility="+avail+" where hallnum ='"+hallnum+"' and time ='"+time+"' and branch ='"+branch+"'";
                 st.addBatch(update);
                 st.addBatch(UpdateM);
                 st.executeBatch();
                 JOptionPane.showMessageDialog(null, "Updated successfully!","",JOptionPane.INFORMATION_MESSAGE);
                   
                 adminMenu ad = new adminMenu();
                 ad.setVisible(true);
                 this.setVisible(false);
                }
                if(check==1){
                 JOptionPane.showMessageDialog(null, "this hall is not Available!","",JOptionPane.ERROR_MESSAGE);
                  
                }
//            }
//                String UpdateM = "update Movie SET Hallnum ='"+hallnum+"' WHERE ( MovieTitle ='"+addMovie.movienameh+"')";
//                addMovie.movienameh 
            
//            int [] arr = st.executeBatch();
           // JOptionPane.showMessageDialog(null, "Updated successfully!","",JOptionPane.INFORMATION_MESSAGE);
        
    }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(),"",JOptionPane.ERROR_MESSAGE);
        }
        finally{
            try{
                rs.close();
                st.close();
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(),"",JOptionPane.ERROR_MESSAGE);
        }
        }}
        else {
            int exit = JOptionPane.showConfirmDialog(this, "Do you want to exit?", "Confirm exit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(exit == JOptionPane.YES_OPTION){
                addMovie a = new addMovie();
                a.setVisible(true);
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_bookbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hallselection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hallselection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hallselection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hallselection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hallselection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookbtn;
    private javax.swing.JButton displaybtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTable hallt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
int movieId;
String movie_id;

}
