/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

/**
 *
 * @author meme
 */
import java.sql.*;
import java.util.Random;
import javax.swing.*;
public class payment extends javax.swing.JFrame {

    /**
     * Creates new form payment
     */
    Connection con = null;
//    ResultSet rs = null;
    PreparedStatement pst = null;
//    Statement stmt = null;
    
    public payment() {
        initComponents();
        con=db.java_db();
        amTxt.setText(""+amount()+" SAR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        fnTxt = new javax.swing.JTextField();
        cnTxt = new javax.swing.JTextField();
        cvcTxt = new javax.swing.JTextField();
        clrBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        dateTxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        amTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(208, 122, 45), 10));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(208, 122, 45));
        jLabel1.setText("Payment");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FILMAX", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kohinoor Bangla", 1, 13), new java.awt.Color(208, 122, 45))); // NOI18N

        jLabel31.setFont(new java.awt.Font("Hei", 0, 13)); // NOI18N
        jLabel31.setText("Full Name:");

        jLabel32.setFont(new java.awt.Font("Hei", 0, 13)); // NOI18N
        jLabel32.setText("Card Number:");

        jLabel33.setFont(new java.awt.Font("Hei", 0, 13)); // NOI18N
        jLabel33.setText("CVC:");

        fnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fnTxtMouseClicked(evt);
            }
        });
        fnTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnTxtActionPerformed(evt);
            }
        });
        fnTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnTxtKeyTyped(evt);
            }
        });

        cnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cnTxtMouseClicked(evt);
            }
        });
        cnTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnTxtActionPerformed(evt);
            }
        });
        cnTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cnTxtKeyTyped(evt);
            }
        });

        cvcTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cvcTxtMouseClicked(evt);
            }
        });
        cvcTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvcTxtActionPerformed(evt);
            }
        });
        cvcTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cvcTxtKeyTyped(evt);
            }
        });

        clrBtn.setText("Clear");
        clrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Hei", 0, 13)); // NOI18N
        jLabel42.setText("Expiration Date:");

        dateTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateTxtMouseClicked(evt);
            }
        });
        dateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTxtActionPerformed(evt);
            }
        });
        dateTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dateTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dateTxtKeyTyped(evt);
            }
        });

        addBtn.setText("Pay");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel42)
                            .addComponent(jLabel33))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cvcTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(dateTxt)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(fnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(cnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cvcTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clrBtn)
                    .addComponent(cancelBtn)
                    .addComponent(addBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        closeBtn.setForeground(new java.awt.Color(208, 122, 45));
        closeBtn.setText("X");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Hei", 0, 13)); // NOI18N
        jLabel34.setText("Amount:");

        amTxt.setEditable(false);
        amTxt.setBackground(new java.awt.Color(255, 255, 255));
        amTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 233, Short.MAX_VALUE)
                        .addComponent(closeBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeBtn)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(amTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fnTxtMouseClicked
        checksDate=dateTxt.getText();
        checksName=fnTxt.getText();
        checksNum=cnTxt.getText();
        checksCVC=cvcTxt.getText();

        if(!checksDate.equals("")){
            add=true;
        }

        if(!checksName.equals("")){
            if(!checkName(checksName)){
                JOptionPane.showMessageDialog(null, "Invalid name!");
                fnTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksCVC.equals("")){
            if(!checkCVC(checksCVC)){
                JOptionPane.showMessageDialog(null, " Invalid CVC!");
                cvcTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksNum.equals("")){
            if(!checkNum(checksNum)){
                JOptionPane.showMessageDialog(null, " Invalid card number!");
                cnTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        }
    }//GEN-LAST:event_fnTxtMouseClicked

    private void fnTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnTxtActionPerformed

    }//GEN-LAST:event_fnTxtActionPerformed

    private void fnTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnTxtKeyReleased

    }//GEN-LAST:event_fnTxtKeyReleased

    private void fnTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnTxtKeyTyped
        //        checksfn = evt.getKeyChar();
    }//GEN-LAST:event_fnTxtKeyTyped

    private void cnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnTxtMouseClicked
        checksDate=dateTxt.getText();
        checksName=fnTxt.getText();
        checksNum=cnTxt.getText();
        checksCVC=cvcTxt.getText();

        if(!checksDate.equals("")){
            add=true;
        }

        if(!checksName.equals("")){
            if(!checkName(checksName)){
                JOptionPane.showMessageDialog(null, "Invalid name!");
                fnTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksCVC.equals("")){
            if(!checkCVC(checksCVC)){
                JOptionPane.showMessageDialog(null, " Invalid CVC!");
                cvcTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksNum.equals("")){
            if(!checkNum(checksNum)){
                JOptionPane.showMessageDialog(null, " Invalid card number!");
                cnTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        }
    }//GEN-LAST:event_cnTxtMouseClicked

    private void cnTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnTxtActionPerformed

    }//GEN-LAST:event_cnTxtActionPerformed

    private void cnTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnTxtKeyTyped
        //      checksmn =evt.getKeyChar();
    }//GEN-LAST:event_cnTxtKeyTyped

    private void cvcTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cvcTxtMouseClicked
        checksDate=dateTxt.getText();
        checksName=fnTxt.getText();
        checksNum=cnTxt.getText();
        checksCVC=cvcTxt.getText();

        if(!checksDate.equals("")){
            add=true;
        }

        if(!checksName.equals("")){
            if(!checkName(checksName)){
                JOptionPane.showMessageDialog(null, "Invalid name!");
                fnTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksCVC.equals("")){
            if(!checkCVC(checksCVC)){
                JOptionPane.showMessageDialog(null, " Invalid CVC!");
                cvcTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksNum.equals("")){
            if(!checkNum(checksNum)){
                JOptionPane.showMessageDialog(null, " Invalid card number!");
                cnTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        }
    }//GEN-LAST:event_cvcTxtMouseClicked

    private void cvcTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvcTxtActionPerformed

        
    }//GEN-LAST:event_cvcTxtActionPerformed

    private void cvcTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cvcTxtKeyTyped
        //      checksln =evt.getKeyChar();

    }//GEN-LAST:event_cvcTxtKeyTyped

    private void clrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrBtnActionPerformed
        fnTxt.setText("");
        cnTxt.setText("");
        cvcTxt.setText("");
        dateTxt.setText("");
    }//GEN-LAST:event_clrBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        bookinghomescreen c = new bookinghomescreen();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void dateTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateTxtMouseClicked
        checksDate=dateTxt.getText();
        checksName=fnTxt.getText();
        checksNum=cnTxt.getText();
        checksCVC=cvcTxt.getText();

        if(!checksDate.equals("")){
            add=true;
        }

        if(!checksName.equals("")){
            if(!checkName(checksName)){
                JOptionPane.showMessageDialog(null, "Invalid name!");
                fnTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksCVC.equals("")){
            if(!checkCVC(checksCVC)){
                JOptionPane.showMessageDialog(null, " Invalid CVC!");
                cvcTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        }
        if(!checksNum.equals("")){
            if(!checkNum(checksNum)){
                JOptionPane.showMessageDialog(null, " Invalid card number!");
                cnTxt.setText("");
                add=false;
            }
            else{
                add=true;
            }
        }
        
    }//GEN-LAST:event_dateTxtMouseClicked

    private void dateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTxtActionPerformed

    }//GEN-LAST:event_dateTxtActionPerformed

    private void dateTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateTxtKeyReleased

    }//GEN-LAST:event_dateTxtKeyReleased

    private void dateTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateTxtKeyTyped

    }//GEN-LAST:event_dateTxtKeyTyped

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirm exit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(response == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_closeBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed

        if(add){
            int response = JOptionPane.showConfirmDialog(null, "Continue with the payment?", "Confirm payment", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(response == JOptionPane.YES_OPTION){
            try{
                String sql = "insert into payment"
                +"(invoiceID, usersname, price, cardNo, CVC,"
                +"fullname)"
                +"values(?,?,?,?,?,?)";
                pst=con.prepareStatement(sql);

                Random rand = new Random(); 
                int random=rand.nextInt((999999999-100000001)+1)+100000001;
                int invoice=random;
                
                pst.setInt(1, invoice);
                pst.setString(2, customerLogin.username);
                pst.setDouble(3,amount());
                pst.setString(4, cnTxt.getText());
                pst.setString(5, cvcTxt.getText());
                pst.setString(6, fnTxt.getText());

                pst.execute();
 
                JOptionPane.showMessageDialog(null, "Payment executed successfully. Thank you!");
                int price = (int)amount();
                int points = (price/4);
                
                String getPoints = "select points from customer where username='"+customerLogin.username+"'";
                PreparedStatement pst1 = con.prepareStatement(getPoints);
                ResultSet rs = pst1.executeQuery();
                int usersPoints=0;
                while(rs.next()){
                usersPoints = rs.getInt("points");
                }
                
                String addPoints = "update customer set points="+(usersPoints+points)+" where username='"+customerLogin.username+"'";
                PreparedStatement pst2 = con.prepareStatement(addPoints);
                pst2.executeUpdate();
                
                String addTicket = "insert into Ticket (idTicket, movieId, ShowDate, hall_num, seatnumber, price, username, showTime, idInvoice) "
                        + "values (?,?,?,?,?,?,?,?,?)";
                
                PreparedStatement pst3 = con.prepareStatement(addTicket);
                
                Random randomNumber = new Random();

                int ticketID =randomNumber.nextInt((9999-1111)+1)+1111;
                
                StringBuilder sb=new StringBuilder();
//                String chosenSeats="";
                
                for(String s : seatBooking.cs){
                    sb.append(s);
                    sb.append(",");
                }
                
                String chosenSeats=sb.toString();
                
//                for(int i = 0; i < seatBooking.cs.size() ; i++){
//                    chosenSeats = seatBooking.cs+"";
//                    if(i!=seatBooking.cs.size()){
//                         chosenSeats = chosenSeats+",";
//                    }
//                }
                
                
                pst3.setInt(1, ticketID);
                pst3.setString(2, seatBooking.id);
                pst3.setString(3, seatBooking.date);
                pst3.setString(4, seatBooking.hn);
                pst3.setString(5, chosenSeats);
                pst3.setDouble(6, price);
                pst3.setString(7, customerLogin.username);
                pst3.setString(8, seatBooking.time);
                pst3.setInt(9, invoice);
                
                pst3.execute();
                
                customerMenu m = new customerMenu();
                m.setVisible(true);
                this.setVisible(false);
                
                int tid = ticketID;
                String mid = seatBooking.id;
                String showdate =seatBooking.date;
                String hallnum = seatBooking.hn;
                String seatnum = chosenSeats;
                double price2 = price;
                String un = customerLogin.username;
                String showtime = seatBooking.time;
                int invoiceId = random;
                
                ticketfile tix = new ticketfile(invoiceId, tid, showdate, hallnum, seatnum, price2, un, showtime, mid);
                tix.writeToFile(tix);
            }

            catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage(), "",JOptionPane.ERROR_MESSAGE);
            }
            finally{
                try{

                    pst.close();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e.getMessage(),"",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        else
            JOptionPane.showMessageDialog(null,"An error occurred, make sure all fields are filled with valid information");
        }
        else{
            fnTxt.setText("");
            cnTxt.setText("");
            cvcTxt.setText("");
            dateTxt.setText("");
        }
            
    }//GEN-LAST:event_addBtnActionPerformed

    private void amTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payment().setVisible(true);
            }
        });
    }
    
    
    public static boolean checkCVC(String checkspn){
     boolean valid=false; 
     if(checkspn.length()==3){
        for (char c : checkspn.toCharArray()){
            if(!Character.isDigit(c)){
                valid = false;
                break;
            }
            else{
                valid=true;
            }
        }
     }
        return valid;   
    }
    
    public static boolean checkNum(String checkspn){
     boolean valid=false; 
     if(checkspn.length()==16){
        for (char c : checkspn.toCharArray()){
            if(!Character.isDigit(c)){
                valid = false;
                break;
            }
            else{
                valid=true;
            }
        }
     }
        return valid;   
    }
    
    public static boolean checkName(String checksfn){
    boolean valid=true;
    for (char c : checksfn.toCharArray()){
        if(Character.isDigit(c))
            valid =false;
    }
    return valid;
    }  
    
    private double amount(){
        
        return seatBooking.numofseats * 40;   
    }
    

    private String checksName="";
    private String checksNum="";
    private String checksCVC="";
    private String checksDate="";


    private static boolean add=true;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField amTxt;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton clrBtn;
    private javax.swing.JTextField cnTxt;
    private javax.swing.JTextField cvcTxt;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JTextField fnTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables

}
